package mcp

import "github.com/mark3labs/mcp-go/mcp"

// allTools returns every MCP tool exposed by the PinchTab MCP server.
func allTools() []mcp.Tool {
	return []mcp.Tool{
		// ── Navigation ──────────────────────────────────────────────
		mcp.NewTool("pinchtab_navigate",
			mcp.WithDescription("Navigate to a URL in the browser"),
			mcp.WithString("url", mcp.Required(), mcp.Description("The URL to navigate to")),
			mcp.WithString("tabId", mcp.Description("Target tab ID (optional, uses current tab if empty)")),
			mcp.WithBoolean("snap", mcp.Description("Return interactive compact snapshot after navigation (saves a round-trip)")),
		),
		mcp.NewTool("pinchtab_snapshot",
			mcp.WithDescription("Get an accessibility tree snapshot of the current page. Use this sparingly: prefer pinchtab_find + action selectors for faster loops."),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
			mcp.WithBoolean("interactive", mcp.Description("Only interactive elements (buttons, links, inputs)")),
			mcp.WithBoolean("compact", mcp.Description("Compact format (most token-efficient)")),
			mcp.WithString("format", mcp.Description("Output format: 'compact' or 'text'")),
			mcp.WithBoolean("diff", mcp.Description("Only changes since last snapshot")),
			mcp.WithString("selector", mcp.Description("Unified selector to scope the snapshot (ref, CSS, XPath, text, find, role, label, placeholder, alt, title, testid, first/last/nth). Selectors resolve in the current frame scope; use pinchtab_frame for iframe content.")),
			mcp.WithNumber("maxTokens", mcp.Description("Maximum estimated tokens in response (e.g. 300)")),
			mcp.WithNumber("depth", mcp.Description("Maximum tree depth (e.g. 3)")),
			mcp.WithBoolean("noAnimations", mcp.Description("Disable animations before capturing the snapshot")),
		),
		mcp.NewTool("pinchtab_frame",
			mcp.WithDescription("Get or set the current frame scope for selector-based actions and snapshots"),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
			mcp.WithString("target", mcp.Description("Frame target: 'main', a snapshot ref, a selector for an iframe element, or a frame name/URL")),
		),
		mcp.NewTool("pinchtab_screenshot",
			mcp.WithDescription("Take a screenshot of the current page. With annotate=true, the response is a JSON envelope with the image plus a list of {ref, role, name, box} so the model can label elements visually and act on the same refs. Use outputPath to write the image to disk instead of returning it inline (avoids context window limits)."),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
			mcp.WithString("selector", mcp.Description("Unified selector. Without annotate it clips the screenshot to the element. With annotate=true it narrows which elements receive overlay boxes (default: all interactive elements).")),
			mcp.WithString("format", mcp.Description("Image format: 'jpeg' (default) or 'png'")),
			mcp.WithNumber("quality", mcp.Description("JPEG quality 0-100 (only for JPEG format)")),
			mcp.WithBoolean("css1x", mcp.Description("When selector is set (without annotate), return element screenshot at CSS pixel size (1x) instead of device pixels")),
			mcp.WithBoolean("annotate", mcp.Description("Overlay numbered ref boxes on interactive elements (or on selector matches). Returns the image plus a structured list of {ref, role, name, box}.")),
			mcp.WithString("outputPath", mcp.Description("Write screenshot to this file path instead of returning inline. Use /tmp/ or a workspace path. Returns the file path on success.")),
		),
		mcp.NewTool("pinchtab_get_text",
			mcp.WithDescription("Extract readable text content from the current page. Inherits the current frame scope for the tab unless no frame is selected."),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
			mcp.WithBoolean("raw", mcp.Description("Return raw text without formatting")),
			mcp.WithString("format", mcp.Description("Response format: 'text'/'plain' for plain text, default JSON envelope")),
			mcp.WithNumber("maxChars", mcp.Description("Maximum characters in response (e.g. 3000)")),
		),

		// ── Interaction ─────────────────────────────────────────────
		mcp.NewTool("pinchtab_click",
			mcp.WithDescription("Click an element. Prefer selector from pinchtab_find.best_ref (e.g. 'e5') to avoid extra snapshots."),
			mcp.WithString("selector", mcp.Description("Unified selector: ref (e.g. 'e5'), CSS, XPath, text, find, role, label, placeholder, alt, title, testid, or first/last/nth. Non-ref selectors resolve in the current frame scope.")),
			mcp.WithString("ref", mcp.Description("(deprecated) Element ref from snapshot — use 'selector' instead")),
			mcp.WithString("query", mcp.Description("Alias for semantic targeting when selector is omitted (example: 'login button' -> find:login button)")),
			mcp.WithString("dialogAction", mcp.Description("Optional one-shot dialog handling for this click: 'accept' or 'dismiss'")),
			mcp.WithString("dialogText", mcp.Description("Optional prompt text used with dialogAction='accept'")),
			mcp.WithNumber("x", mcp.Description("Optional X coordinate for coordinate click")),
			mcp.WithNumber("y", mcp.Description("Optional Y coordinate for coordinate click")),
			mcp.WithNumber("nodeId", mcp.Description("Optional backend node ID to target directly")),
			mcp.WithBoolean("waitNav", mcp.Description("Wait for navigation after the click when the element triggers a page change")),
			mcp.WithString("mode", mcp.Description("Optional click delivery override: 'dom' for element.click() or 'dispatch' for synthetic click events on the target")),
			mcp.WithBoolean("snap", mcp.Description("Return interactive compact snapshot after click (saves a round-trip)")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_type",
			mcp.WithDescription("Type text into an input element"),
			mcp.WithString("selector", mcp.Description("Unified selector: ref (e.g. 'e5'), CSS, XPath, text, or semantic. Non-ref selectors resolve in the current frame scope.")),
			mcp.WithString("ref", mcp.Description("(deprecated) Element ref from snapshot — use 'selector' instead")),
			mcp.WithString("query", mcp.Description("Alias for semantic targeting when selector is omitted")),
			mcp.WithString("text", mcp.Required(), mcp.Description("Text to type")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_press",
			mcp.WithDescription("Press a keyboard key (Enter, Tab, Escape, etc.)"),
			mcp.WithString("key", mcp.Required(), mcp.Description("Key to press (e.g., 'Enter', 'Tab', 'Escape')")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_hover",
			mcp.WithDescription("Hover over an element"),
			mcp.WithString("selector", mcp.Description("Unified selector: ref (e.g. 'e5'), CSS, XPath, text, or semantic. Non-ref selectors resolve in the current frame scope.")),
			mcp.WithString("ref", mcp.Description("(deprecated) Element ref from snapshot — use 'selector' instead")),
			mcp.WithString("query", mcp.Description("Alias for semantic targeting when selector is omitted")),
			mcp.WithNumber("x", mcp.Description("Optional X coordinate for coordinate hover")),
			mcp.WithNumber("y", mcp.Description("Optional Y coordinate for coordinate hover")),
			mcp.WithNumber("nodeId", mcp.Description("Optional backend node ID to target directly")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_focus",
			mcp.WithDescription("Focus an element"),
			mcp.WithString("selector", mcp.Description("Unified selector: ref (e.g. 'e5'), CSS, XPath, text, or semantic. Non-ref selectors resolve in the current frame scope.")),
			mcp.WithString("ref", mcp.Description("(deprecated) Element ref from snapshot — use 'selector' instead")),
			mcp.WithString("query", mcp.Description("Alias for semantic targeting when selector is omitted")),
			mcp.WithNumber("nodeId", mcp.Description("Optional backend node ID to target directly")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_select",
			mcp.WithDescription("Select a dropdown option by value or visible text"),
			mcp.WithString("selector", mcp.Description("Unified selector for the select element. Non-ref selectors resolve in the current frame scope.")),
			mcp.WithString("ref", mcp.Description("(deprecated) Element ref from snapshot — use 'selector' instead")),
			mcp.WithString("query", mcp.Description("Alias for semantic targeting when selector is omitted")),
			mcp.WithString("value", mcp.Required(), mcp.Description("Option value or visible text to select")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
			mcp.WithBoolean("snap", mcp.Description("Return interactive compact snapshot after select (saves a round-trip)")),
		),
		mcp.NewTool("pinchtab_scroll",
			mcp.WithDescription("Scroll the page or an element. For element targeting + pixel deltas, this automatically uses wheel semantics for smoother behavior."),
			mcp.WithString("selector", mcp.Description("Unified selector for element to scroll (omit for page scroll). Non-ref selectors resolve in the current frame scope.")),
			mcp.WithString("ref", mcp.Description("(deprecated) Element ref to scroll — use 'selector' instead")),
			mcp.WithString("query", mcp.Description("Alias for semantic targeting when selector is omitted")),
			mcp.WithNumber("pixels", mcp.Description("Number of pixels to scroll (positive=down, negative=up)")),
			mcp.WithNumber("deltaX", mcp.Description("Horizontal wheel delta for precise scrolling")),
			mcp.WithNumber("deltaY", mcp.Description("Vertical wheel delta for precise scrolling")),
			mcp.WithString("direction", mcp.Description("Convenience direction: 'up' or 'down'")),
			mcp.WithNumber("steps", mcp.Description("Multiplier for direction-based scrolling (default 1)")),
			mcp.WithNumber("x", mcp.Description("Optional X coordinate for wheel target")),
			mcp.WithNumber("y", mcp.Description("Optional Y coordinate for wheel target")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_scroll_into_view",
			mcp.WithDescription("Scroll a target element into view and return geometry details for stable follow-up actions."),
			mcp.WithString("selector", mcp.Description("Unified selector: ref (e.g. 'e5'), CSS, XPath, text, or semantic. Non-ref selectors resolve in the current frame scope.")),
			mcp.WithString("ref", mcp.Description("(deprecated) Element ref — use 'selector' instead")),
			mcp.WithString("query", mcp.Description("Alias for semantic targeting when selector is omitted")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_fill",
			mcp.WithDescription("Fill an input field directly via JavaScript dispatch"),
			mcp.WithString("selector", mcp.Description("Unified selector: ref (e.g. 'e5'), CSS, XPath, text, or semantic. Non-ref selectors resolve in the current frame scope.")),
			mcp.WithString("ref", mcp.Description("(deprecated) Element ref — use 'selector' instead")),
			mcp.WithString("query", mcp.Description("Alias for semantic targeting when selector is omitted")),
			mcp.WithString("value", mcp.Required(), mcp.Description("Value to fill")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
			mcp.WithBoolean("snap", mcp.Description("Return interactive compact snapshot after fill (saves a round-trip)")),
		),

		// ── Keyboard (no selector — targets focused element) ────────
		mcp.NewTool("pinchtab_keyboard_type",
			mcp.WithDescription("Type text at the currently focused element via keystroke events (keyDown + keyUp per character)"),
			mcp.WithString("text", mcp.Required(), mcp.Description("Text to type")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_keyboard_inserttext",
			mcp.WithDescription("Insert text at the currently focused element without key events (paste-like)"),
			mcp.WithString("text", mcp.Required(), mcp.Description("Text to insert")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_keydown",
			mcp.WithDescription("Hold a key down (e.g. modifier keys like Control, Shift, Alt)"),
			mcp.WithString("key", mcp.Required(), mcp.Description("Key to hold down (e.g. 'Control', 'Shift', 'Alt', 'a')")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_keyup",
			mcp.WithDescription("Release a held key"),
			mcp.WithString("key", mcp.Required(), mcp.Description("Key to release (e.g. 'Control', 'Shift', 'Alt', 'a')")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),

		// ── Content ─────────────────────────────────────────────────
		mcp.NewTool("pinchtab_eval",
			mcp.WithDescription("Execute JavaScript in the browser and return the result. This is not frame-scoped; current pinchtab_frame state does not change evaluation context."),
			mcp.WithString("expression", mcp.Required(), mcp.Description("JavaScript expression to evaluate")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_pdf",
			mcp.WithDescription("Export the current page as a PDF (returns base64-encoded PDF)"),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
			mcp.WithBoolean("landscape", mcp.Description("Landscape orientation")),
			mcp.WithNumber("scale", mcp.Description("Print scale 0.1-2.0 (default: 1.0)")),
			mcp.WithString("pageRanges", mcp.Description("Pages to export (e.g., '1-3,5')")),
		),
		mcp.NewTool("pinchtab_find",
			mcp.WithDescription("Find elements by natural-language query. Returns best_ref and selector hints that should be reused in action tools."),
			mcp.WithString("query", mcp.Required(), mcp.Description("Text or CSS selector to search for")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),

		// ── Tab Management ──────────────────────────────────────────
		mcp.NewTool("pinchtab_list_tabs",
			mcp.WithDescription("List all open browser tabs"),
		),
		mcp.NewTool("pinchtab_close_tab",
			mcp.WithDescription("Close a browser tab"),
			mcp.WithString("tabId", mcp.Description("ID of the tab to close; uses the current/default tab when omitted")),
		),
		mcp.NewTool("pinchtab_health",
			mcp.WithDescription("Check PinchTab server health status"),
		),
		mcp.NewTool("pinchtab_cookies",
			mcp.WithDescription("Get cookies for the current page"),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_connect_profile",
			mcp.WithDescription("Get the user-facing connect URL and instance status for a profile"),
			mcp.WithString("profile", mcp.Required(), mcp.Description("Profile name or profile ID")),
		),

		// ── Utility ─────────────────────────────────────────────────
		mcp.NewTool("pinchtab_wait",
			mcp.WithDescription("Wait for a specified number of milliseconds"),
			mcp.WithNumber("ms", mcp.Required(), mcp.Description("Milliseconds to wait (max 30000)")),
		),
		mcp.NewTool("pinchtab_wait_for_selector",
			mcp.WithDescription("Wait for an element matching a selector to appear or disappear on the page"),
			mcp.WithString("selector", mcp.Required(), mcp.Description("Unified selector to wait for (CSS, XPath, text, or ref)")),
			mcp.WithNumber("timeout", mcp.Description("Timeout in milliseconds (default: 10000, max: 30000)")),
			mcp.WithString("state", mcp.Description("Element state to wait for: 'visible' (default) or 'hidden'")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_wait_for_text",
			mcp.WithDescription("Wait for specific text to appear on the page"),
			mcp.WithString("text", mcp.Required(), mcp.Description("Text to wait for")),
			mcp.WithNumber("timeout", mcp.Description("Timeout in milliseconds (default: 10000, max: 30000)")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_wait_for_url",
			mcp.WithDescription("Wait for the page URL to match a glob pattern"),
			mcp.WithString("url", mcp.Required(), mcp.Description("URL glob pattern to match (e.g. '**/dashboard')")),
			mcp.WithNumber("timeout", mcp.Description("Timeout in milliseconds (default: 10000, max: 30000)")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_wait_for_load",
			mcp.WithDescription("Wait for a page load state"),
			mcp.WithString("load", mcp.Required(), mcp.Description("Load state: 'ready-state' (readyState=complete), 'content-loaded' (readyState in {interactive, complete}), or 'network-idle' (0 in-flight requests for 500ms)")),
			mcp.WithNumber("timeout", mcp.Description("Timeout in milliseconds (default: 10000, max: 30000)")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_wait_for_function",
			mcp.WithDescription("Wait for a JavaScript expression to return a truthy value"),
			mcp.WithString("fn", mcp.Required(), mcp.Description("JavaScript expression to evaluate")),
			mcp.WithNumber("timeout", mcp.Description("Timeout in milliseconds (default: 10000, max: 30000)")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),

		// ── Network Monitoring ──────────────────────────────────────
		mcp.NewTool("pinchtab_network",
			mcp.WithDescription("List recent network requests captured from the browser. Returns method, status, URL, type, size, and timing for each request."),
			mcp.WithString("tabId", mcp.Description("Target tab ID (optional, uses current tab if empty)")),
			mcp.WithString("filter", mcp.Description("URL pattern filter (substring match)")),
			mcp.WithString("method", mcp.Description("HTTP method filter (GET, POST, etc)")),
			mcp.WithString("status", mcp.Description("Status code range filter (e.g. '4xx', '5xx', '200')")),
			mcp.WithString("type", mcp.Description("Resource type filter (xhr, fetch, document, stylesheet, script, image, etc)")),
			mcp.WithNumber("limit", mcp.Description("Maximum number of entries to return")),
			mcp.WithNumber("bufferSize", mcp.Description("Per-tab buffer size for new capture (default from config, typically 100)")),
		),
		mcp.NewTool("pinchtab_network_detail",
			mcp.WithDescription("Get full details of a specific network request including headers, timing, and optionally the response body"),
			mcp.WithString("requestId", mcp.Required(), mcp.Description("The request ID from pinchtab_network results")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
			mcp.WithBoolean("body", mcp.Description("Include response body (can be large)")),
		),
		mcp.NewTool("pinchtab_network_clear",
			mcp.WithDescription("Clear captured network data for a tab or all tabs"),
			mcp.WithString("tabId", mcp.Description("Target tab ID (optional, clears all if empty)")),
		),
		mcp.NewTool("pinchtab_network_route",
			mcp.WithDescription("Install a request interception rule on a tab. Action 'abort' blocks matching requests, 'fulfill' returns a mocked response body, 'continue' passes through. Fulfill is BLOCKED on hosts in security.allowedDomains (the operator's authorized/sensitive surfaces) and ALLOWED on other hosts; matched fulfill rules on allowlisted hosts fall through to a real network fetch."),
			mcp.WithString("tabId", mcp.Required(), mcp.Description("Target tab ID")),
			mcp.WithString("pattern", mcp.Required(), mcp.Description("URL pattern: substring (no wildcards) or glob ('*', '?')")),
			mcp.WithString("action", mcp.Description("'continue' (default), 'abort', or 'fulfill'")),
			mcp.WithString("body", mcp.Description("Response body (with action=fulfill). Sent verbatim; not auto-encoded.")),
			mcp.WithString("contentType", mcp.Description("Response Content-Type for fulfill (default application/json)")),
			mcp.WithNumber("status", mcp.Description("Response status code for fulfill (default 200)")),
			mcp.WithString("resourceType", mcp.Description("Limit to a CDP resource category (e.g. script, image, xhr, fetch, stylesheet)")),
			mcp.WithString("method", mcp.Description("Limit to an HTTP method (GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS). Fulfill rules without method skip OPTIONS preflights to avoid breaking or bypassing CORS.")),
		),
		mcp.NewTool("pinchtab_network_unroute",
			mcp.WithDescription("Remove a tab's interception rule by pattern, or all rules if pattern is omitted"),
			mcp.WithString("tabId", mcp.Required(), mcp.Description("Target tab ID")),
			mcp.WithString("pattern", mcp.Description("Pattern to remove (omit to clear all rules)")),
		),

		// ── Recording ───────────────────────────────────────────────
		mcp.NewTool("pinchtab_record_start",
			mcp.WithDescription("Start recording browser activity. Requires security.allowScreencast. GIF works without ffmpeg; WebM/MP4 need ffmpeg."),
			mcp.WithString("file", mcp.Required(), mcp.Description("Output file path (.gif, .webm, or .mp4)")),
			mcp.WithNumber("fps", mcp.Description("Frames per second 1-30 (default: 5)")),
			mcp.WithNumber("quality", mcp.Description("JPEG capture quality 1-100 (default: 80)")),
			mcp.WithNumber("scale", mcp.Description("Resolution scale 0-1.0 (default: 1.0)")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
		mcp.NewTool("pinchtab_record_stop",
			mcp.WithDescription("Stop recording and save the encoded file. Encoding may take a while for long recordings."),
			mcp.WithString("file", mcp.Required(), mcp.Description("Output file path (must match the format from record_start)")),
		),
		mcp.NewTool("pinchtab_record_status",
			mcp.WithDescription("Check active recording status (format, fps, duration, frame count)"),
		),

		// ── Dialog ──────────────────────────────────────────────────
		mcp.NewTool("pinchtab_dialog",
			mcp.WithDescription("Handle a JavaScript dialog (alert, confirm, prompt). Accept or dismiss the currently open dialog."),
			mcp.WithString("action", mcp.Required(), mcp.Description("Action to take: 'accept' or 'dismiss'")),
			mcp.WithString("text", mcp.Description("Text to enter for prompt dialogs (only used with accept)")),
			mcp.WithString("tabId", mcp.Description("Target tab ID")),
		),
	}
}
